/*
Croneworlds Landmarks
*/
/obj/effect/landmark/cronespawner
	name = "cronespawner"

/obj/effect/landmark/cronespawner

/obj/effect/landmark/cronespawner/New()
	var/landmarkrandom = rand(1, 19)
	switch(landmarkrandom) 
		if(1)
			new /mob/living/simple_animal/hostile/void_dweller(loc)
			new /obj/item/device/soulstone(loc)
		if(2)
			new /mob/living/simple_animal/hostile/shadow(loc)
		if(3)
			new /mob/living/simple_animal/hostile/necro/zombie/leatherman/void(loc)
		if(4)
			new /obj/item/clothing/head/ushanka(loc)
		if(5)
			new /obj/item/clothing/under/gladiator(loc)
		if(6)
			new /obj/item/clothing/head/helmet/gladiator(loc)
			new /obj/item/weapon/metal_blade(loc)
		if(7)
			new /mob/living/simple_animal/hostile/retaliate/warpentity/predator(loc) //Putting that instead of nightblood. Nightblood currently steals ghosts, and this is more dangerous.
		if(8)
			new /obj/item/weapon/chainsword/chaos_chainsword(loc)
		if(9)
			new /obj/item/weapon/choppa(loc)
			if(prob(40)) 
				new /obj/item/device/soulstone(loc)
		if(10)
			new /obj/item/weapon/circular_saw(loc)
			new /obj/item/weapon/dice/d20/cursed(loc)
		if(11)
			new /obj/item/weapon/powersword/burning(loc)
		if(12)
			new /obj/item/device/mass_spectrometer(loc)
		if(13)
			new /obj/machinery/doppler_array(loc)
		if(14)
			new /obj/machinery/telepad(loc)
			new /obj/item/weapon/bikehorn(loc)
		if(15)
			new /obj/structure/closet/cabinet/medivault(loc)
		if(16)
			new /mob/living/simple_animal/hostile/retaliate/warpentity/hulk(loc)
		if(17)
			new /mob/living/simple_animal/hostile/humanoid/russian/ranged/void(loc)
		if(18)
			new /mob/living/simple_animal/hostile/dark_ghost(loc)
		if(19)
			new /mob/living/simple_animal/hostile/giant_spider/hunter/void(loc)
			new /obj/item/weapon/powersword/eldar(loc)
	qdel(src)